services:
  redis-stack:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
#  cs554-webapp:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env.local
#    ports:
#      - "3000:3000"
